// data.js

const imagesData = [
    { id: 1, url: '/Images/itpa1.webp', alt: 'Image 1' },
    // { id: 2, url: /Images/itpa2.JPG', alt: 'Image 2' },
    { id: 3, url: '/Images/itpa3.JPG', alt: 'Image 3' },
    { id: 4, url: '/Images/itpa4.JPG', alt: 'Image 4' },
    { id: 5, url: '/Images/itpa5.JPG', alt: 'Image 5' },
    { id: 6, url: '/Images/itpa6.JPG', alt: 'Image 6' },
    { id: 7, url: '/Images/itpa7.JPG', alt: 'Image 7' },
    { id: 8, url: '/Images/itpa8.JPG', alt: 'Image 8' },
    { id: 9, url: '/Images/itpa9.JPG', alt: 'Image 9' },
    { id: 10, url: '/Images/itpa10.JPG', alt: 'Image 10' },
    { id: 11, url: '/Images/itpa11.JPG', alt: 'Image 11' },
    // { id: 12, url: '/src/assets/Images/itpa12.JPG', alt: 'Image 12' },
    // { id: 13, url: '/src/assets/Images/itpa13.JPG', alt: 'Image 13' },
    // { id: 14, url: '/src/assets/Images/itpa14.JPG', alt: 'Image 14' },
    // { id: 15, url: '/src/assets/Images/itpa15.JPG', alt: 'Image 15' },
    // { id: 16, url: '/src/assets/Images/itpa16.JPG', alt: 'Image 16' },
    // { id: 17, url: '/src/assets/Images/itpa17.JPG', alt: 'Image 17' },
    // { id: 18, url: '/src/assets/Images/itpa18.JPG', alt: 'Image 18' },
    // { id: 19, url: '/src/assets/Images/itpa19.JPG', alt: 'Image 19' },
    // { id: 20, url: '/src/assets/Images/itpa20.JPG', alt: 'Image 20' },
    // { id: 21, url: '/src/assets/Images/itpa21.JPG', alt: 'Image 21' },
    // { id: 22, url: '/src/assets/Images/itpa22.JPG', alt: 'Image 22' },
    // { id: 23, url: '/src/assets/Images/itpa23.JPG', alt: 'Image 23' },
    // { id: 24, url: '/src/assets/Images/itpa24.JPG', alt: 'Image 24' },
    // { id: 25, url: '/src/assets/Images/itpa25.JPG', alt: 'Image 25' },
    // { id: 26, url: '/src/assets/Images/itpa26.JPG', alt: 'Image 26' },
    // { id: 27, url: '/src/assets/Images/itpa27.JPG', alt: 'Image 27' },
    // { id: 28, url: '/src/assets/Images/itpa28.JPG', alt: 'Image 28' },
    // { id: 29, url: '/src/assets/Images/itpa29.JPG', alt: 'Image 29' },
    // { id: 30, url: '/src/assets/Images/itpa30.JPG', alt: 'Image 30' },
    // { id: 31, url: '/src/assets/Images/itpa31.JPG', alt: 'Image 31' },
    // { id: 32, url: '/src/assets/Images/itpa32.JPG', alt: 'Image 32' },
    // { id: 33, url: '/src/assets/Images/itpa33.JPG', alt: 'Image 33' },
    // { id: 34, url: '/src/assets/Images/itpa34.JPG', alt: 'Image 34' },
    // { id: 35, url: '/src/assets/Images/itpa35.JPG', alt: 'Image 35' },
    // { id: 36, url: '/src/assets/Images/itpa36.JPG', alt: 'Image 36' },
    // { id: 37, url: '/src/assets/Images/itpa37.JPG', alt: 'Image 37' },
    // { id: 38, url: '/src/assets/Images/itpa38.JPG', alt: 'Image 38' },
];

export default imagesData;
